export const FETCH_EVENT_TIMES = 'FETCH_EVENT_TIMES'
export const FETCH_EVENTS = 'FETCH_EVENTS'
export const SET_CURRENT_EVENT = 'SET_CURRENT_EVENT'
export const SET_CURRENT_TIMESLOT = 'SET_CURRENT_TIMESLOT'
export const SET_RESERVATION_600 = 'SET_RESERVATION_600'
export const SET_RESERVATION_800 = 'SET_RESERVATION_800'
export const SET_FORM_STEP = 'SET_FORM_STEP'

